version: '3'

services:
  elpis-back:
    build:
      context: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./elpis-back/.env
    networks:
      - elpis-network

  elpis-front:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_HOST=https://api.elpis.tn/
    env_file:
      - ./elpis-front/.env
    networks:
      - elpis-network
    volumes:
      - ./elpis-front/build:/var/www/elpis  # Mount build directory to /var/www/elpis on VPS
    depends_on:
      - elpis-back  # Ensure backend starts first

networks:
  elpis-network:
    driver: bridge
