version: '3'

services:
  elpis-back:
    build:
      context: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./elpis-back/.env
    networks:
      - elpis-network

  elpis-front:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_HOST=https://api.elpis.tn/
    env_file:
      - ./elpis-front/.env
    command: ["sh", "-c", "npm install && npm run build"]
    networks:
      - elpis-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./elpis-front/build:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt:ro

    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - elpis-front
      - elpis-back
    restart: always
    networks:
      - elpis-network

networks:
  elpis-network:
    driver: bridge
