
services:
  elpis-back:
    build:
      context: ./elpis-back
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./elpis-back/.env
    networks:
      - default

  elpis-front:
    build:
      context: ./elpis-front
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_HOST=https://api.elpis.tn/
    env_file:
      - ./elpis-front/.env
    depends_on:
      - elpis-back
    networks:
      - default

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./elpis-front/build:/usr/share/nginx/html  # React build
    ports:
      - "80:80"
    depends_on:
      - elpis-front
      - elpis-back
    networks:
      - default
    restart: always

networks:
  default:
    driver: bridge
