version: '3.8'

services:
  elpis-app:
    build: .
    ports:
      - "4000:4000"  # Backend port
      - "3000:3000"  # Frontend port
    environment:
      - NODE_ENV=development
    # Load environment variables from the .env files
    env_file:
      - ./elpis-back/.env
      - ./elpis-front/.env
