version: '3.3'

services:
  elpis-back:
    build:
      context: ./elpis-back
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./elpis-back/.env

  elpis-front:
    build:
      context: ./elpis-front
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_HOST=https://api.elpis.tn/
    env_file:
      - ./elpis-front/.env
    depends_on:
      - elpis-back

networks:
  default:
    driver: bridge
