services:
  elpis-app:
    build: .
    ports:
      - "4000:4000"  # Backend port
      - "3000:3000"  # Frontend port
    environment:
      - NODE_ENV=development
    env_file:
      - ./elpis-back/.env
      - ./elpis-front/.env
    volumes:
      - .:/app  # Bind mount for live editing (optional)

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./elpis-front/build:/usr/share/nginx/html  # Serving React build
    ports:
      - "80:80"
    restart: always
